###
DELETE http://localhost:3000/songs/3

###
GET http://localhost:3000/songs/3
Accept: application/json

###
PATCH http://localhost:3000/songs/3
Content-Type: application/json

{
  "title": "Порш3"
}

###
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "911",
  "artists": [1],
  "releasedDate": "2025-09-29",
  "duration": "02:34"
}

###
GET localhost:3000/songs?page=1&limit=10


###
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Порш11",
  "songs": [22, 23],
  "user": 2
}
