
// Songs
###
DELETE http://localhost:3000/songs/3

###
GET http://localhost:3000/songs/3
Accept: application/json

###
PATCH http://localhost:3000/songs/3
Content-Type: application/json

{
  "title": "Порш3"
}

### Create Song
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "911",
  "artists": [1],
  "releasedDate": "2025-09-29",
  "duration": "02:34"
}

### Get all songs
GET localhost:3000/songs?page=1&limit=10

// Playlists

### Create Playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Порш11",
  "songs": [22, 23],
  "user": 2
}

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "Artem",
"lastName": "Kosyrev",
"email": "cosinusgradusov90@gmail.com",
"password": "123456"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "cosinusgradusov90@gmail.com",
  "password": "123456"
}

### Get Profile
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvc2ludXNncmFkdXNvdjkwQGdtYWlsLmNvbSIsInN1YiI6MSwiaWF0IjoxNzU0NDk5OTA5LCJleHAiOjE3NTQ1MDM1MDl9.A8YUesOvsMigN3kGz2UWbhJKqgkhpvh1jMBn3pYSmTo
